apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  annotations:
    service.kubernetes.io/ibm-load-balancer-cloud-provider-enable-features: "ipvs"
spec:
  type: NodePort
  selector:
      app: nginx-deployment
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 80
  externalTrafficPolicy: Local
